# Generated by Django 3.2.7 on 2021-10-16 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('72cfcda6-86c2-4d2f-97d8-b9bc50e0f538'), editable=False, primary_key=True, serialize=False),
        ),
    ]
