# Generated by Django 3.2.7 on 2021-10-23 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
        ('base_settings', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root_folder',
            field=models.ForeignKey(db_constraint=False, default='03cc78db-e0d5-4aba-a534-bc7d35957550', on_delete=django.db.models.deletion.CASCADE, to='filesystem.folder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('afeeeb11-e931-44ed-95a6-db5f72cee542'), editable=False, primary_key=True, serialize=False),
        ),
    ]
