# Generated by Django 3.2.8 on 2021-10-25 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base_settings', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('6693a098-dbfb-45b3-9903-bc7be0a8c8c5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
