# Generated by Django 3.2.7 on 2021-11-02 17:09

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import filesystem.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filesystem.folder')),
            ],
        ),
        migrations.CreateModel(
            name='FolderRootOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'folder_root_owner',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', filesystem.fields.UniqueNameFileField(storage=django.core.files.storage.FileSystemStorage(base_url='/storage/', location='D:\\python_projects\\remote-storage\\backend\\storage'), upload_to='%Y/%m/%d/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.folder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='folderrootowner',
            constraint=models.UniqueConstraint(fields=('root', 'user'), name='unique_root'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name', 'parent', 'owner'), name='unique_folder'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'parent', 'owner'), name='unique_file'),
        ),
    ]
