# Generated by Django 3.2.8 on 2021-12-04 20:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import filesystem.fields
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_space', models.PositiveBigIntegerField(default=0)),
                ('available_space', models.PositiveBigIntegerField(default=5368709120)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesystem.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=filesystem.fields.UniqueNameFileField(storage=django.core.files.storage.FileSystemStorage(base_url='/storage/', location=pathlib.PureWindowsPath('D:/Daniil/Works/remote-storage/backend/storage')), upload_to='%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='FolderRootOwner',
        ),
        migrations.AddConstraint(
            model_name='userstorageinfo',
            constraint=models.UniqueConstraint(fields=('root', 'user'), name='unique_root'),
        ),
    ]
