# Generated by Django 3.2.7 on 2021-11-23 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name = 'FolderRootOwner',
            new_name = 'UserStorageInfo'),
        migrations.AddField(
            model_name='UserStorageInfo',
            name = 'used_space',
            field = models.PositiveBigIntegerField(default=0)),
        migrations.AddField(
            model_name='UserStorageInfo',
            name = 'available_space',
            field = models.PositiveBigIntegerField(default=5368709120)),
        migrations.AddConstraint(
            model_name='UserStorageInfo',
            constraint=models.UniqueConstraint(fields=('root', 'user'), name='unique_root'),
        ),
    ]
