# Generated by Django 3.2.7 on 2021-12-12 17:23

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import filesystem.fields
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesystem', '0002_auto_20211204_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='root',
            field=models.ForeignKey(default='6693a098-dbfb-45b3-9903-bc7be0a8c8c5', on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_root_folder', to='filesystem.folder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_folder', to='filesystem.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=filesystem.fields.UniqueNameFileField(storage=django.core.files.storage.FileSystemStorage(base_url='/storage/', location=pathlib.PureWindowsPath('D:/python_projects/remote-storage/backend/storage')), upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_parent_folder', to='filesystem.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_folder', to='filesystem.folder'),
        ),
        migrations.AlterField(
            model_name='userstorageinfo',
            name='root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='filesystem.folder'),
        ),
        migrations.AlterField(
            model_name='userstorageinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SharedFilesystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('shared_root', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filesystem.folder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sharedfilesystems',
            constraint=models.UniqueConstraint(fields=('shared_root', 'allowed_user'), name='unique_share'),
        ),
    ]
