# Generated by Django 3.2.7 on 2021-12-15 15:31

import django.core.files.storage
from django.db import migrations
import filesystem.fields
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_auto_20211204_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data',
            field=filesystem.fields.UniqueNameFileField(storage=django.core.files.storage.FileSystemStorage(base_url='/storage/', location=pathlib.PureWindowsPath('C:/code_projects/git_projects/remote-storage/backend/storage')), upload_to='%Y/%m/%d/'),
        ),
    ]
