# Generated by Django 3.2.7 on 2021-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0002_alter_folder_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_file',
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_folder',
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('name', 'parent', 'owner'), name='unique_file'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name', 'parent', 'owner'), name='unique_folder'),
        ),
    ]
