# Generated by Django 3.2.7 on 2021-12-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0003_alter_file_data'),
        ('filesystem', '0004_alter_file_data'),
        ('filesystem', '0004_fileusage'),
    ]

    operations = [
    ]