# Generated by Django 3.2.7 on 2021-12-19 20:37

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import filesystem.fields
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filesystem', '0005_merge_20211219_2332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedFilesystems',
            new_name='SharedStorages',
        ),
        migrations.RemoveConstraint(
            model_name='sharedstorages',
            name='unique_share',
        ),
        migrations.RemoveField(
            model_name='sharedstorages',
            name='shared_root',
        ),
        migrations.AddField(
            model_name='sharedstorages',
            name='storage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='filesystem.userstorageinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='data',
            field=filesystem.fields.UniqueNameFileField(storage=django.core.files.storage.FileSystemStorage(base_url='/storage/', location=pathlib.PureWindowsPath('D:/python_projects/remote-storage/backend/storage')), upload_to='%Y/%m/%d/'),
        ),
        migrations.AddConstraint(
            model_name='sharedstorages',
            constraint=models.UniqueConstraint(fields=('storage', 'allowed_user'), name='unique_share'),
        ),
    ]
