FROM node:16-alpine AS builder

WORKDIR /app/client

COPY ./client/package.json .

RUN npm install

COPY ./client .

RUN npm run build

FROM python:3.8-slim

RUN apt update
ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY ./backend .

COPY --from=builder /app/client/build /app/client/build

RUN pip install --no-cache-dir -r requirements.txt && \
    python manage.py makemigrations && \
    python manage.py migrate
